#!/bin/bash

echo "This will partially run meowton on a PC to speed up development. Crude but effective."

if [ "$UID" != "0" ]; then
	echo "Run as root"
	exit 1
fi

cd micropython
find | entr -r micropython -c "import sys;sys.path.append('lib');" main.py
